---
- name: Delete alfresco dir for sec_installation
  shell: rm -rf /data/wwwroot/alfresco

- name: Clone alfresco in Websoft9 
  git:
    repo: "{{alfresco_git_url}}"
    dest: "/data/wwwroot/alfresco"
    version: dev

- name: Create dir for erpnext
  file: 
    state: directory
    path: "{{item}}"
  loop: 
    - /data/wwwroot/alfresco/volumes
    - /data/db/postgresql

- name: Run docker-compose 
  shell: | 
    docker-compose -f docker-compose-production.yml up -d
    sleep 30
  args:
    chdir: /data/wwwroot/alfresco

- name: Set soft link for erpnext
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
    force: yes
  with_items:
  - {src: /data/wwwroot/alfresco/volumes/postgres/data/,dest: /data/db/postgresql/data}
  - {src: /data/wwwroot/alfresco/volumes/postgres/logs/,dest: /data/db/postgresql/logs}
  - {src: /data/wwwroot/alfresco/volumes/postgres/logs/,dest: /data/logs/postgresql}

# check service and version
- name: Check alfresco service 
  shell: >
    docker inspect  --format='{{.Name}} status {{.State.Status}}' $(docker ps -aq) |cut -b1 --complement
  register: check_alfresco_service
  notify: check_alfresco_service
    
- name: Check alfresco version
  shell: |
    sudo echo "alfresco version:" $(docker images |grep alfresco-share |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  

- name: Check activemq version
  shell: |
    sudo echo "activemq version:" $(docker images |grep alfresco-activemq |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  

- name: Check postgresql version
  shell: |
    sudo echo "postgresql version:" $(docker images |grep postgres |awk '{print $2}') |sudo tee -a /data/logs/install_version.txt  

    